### ISSUE TITLE
Complete & Proofread Documentation

### ISSUE THREAD

**Issue by ClarkThyLord** [ClarkThyLord/Voxel-Core#18]
Documentation found in script needs to be completed and proofread.

**Comment by anti-meta-github** [comment]
I'll try and do this. Is there a discord or something where I can ask questions in case I need clarification? I might ask too frequently and clutter up the issue.

**Comment by ClarkThyLord** [comment]
Rework should be fully documented and following the [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html); Also the wiki has been updated for 3.0.0

If you feel anything is lacking, don't hesitate to say so

**Comment by ClarkThyLord** [comment]
I have prototyped some systems, but I like nothing. I'll keep working on it.

Thinking of adding a hashmap to VoxelObjects storing the orientation of the voxel or using the last bits of the voxel id for a bit flag indicating its orientation
