### ISSUE TITLE
docs?

### ISSUE THREAD

**Issue by jasonswearingen** [ClarkThyLord/Voxel-Core#29]
Just started learning godot (today) so maybe it'll be more obvious once I learn it, but maybe add some docs or a tutorial guide?  

Doesn't need to be fancy, just a quick guide on how to do what you did in your intro video might be enough.

**Comment by ClarkThyLord** [comment]
Sure thing, a good chunk of the scripts are already documented, but I'll create a more accessible guide in this repositories wiki 😄

**Comment by ClarkThyLord** [comment]
done, https://github.com/ClarkThyLord/Voxel-Core/wiki
