### ISSUE TITLE
Ability to Import Files / Palettes to VoxelSets

### ISSUE THREAD

**Issue by ClarkThyLord** [ClarkThyLord/Voxel-Core#39]
Add the ability to import files / palettes to VoxelSets.

- [x] images
- [x] vox files
- [x]  gpl files (gimp palettes)

**Comment by anti-meta-github** [comment]
For images, maybe we can follow how Material Maker does it where you can import an image and use a color picker on it? Here's a [video of how it's used](https://www.youtube.com/watch?v=PY-fCt1j2Ag&t=99s). Here's the [GDScript](https://github.com/RodZill4/material-maker/blob/f0b58398c8d2ea88619902d35484095b3b8f936c/material_maker/widgets/gradient_editor/gradient_editor.gd) (not sure if I got it right). Maybe we can make it so it'll take the image's data and automatically add it to VoxelSet if the user wants?

For gimp palletes, here's the [source code of how they load it](https://gitlab.gnome.org/GNOME/gimp/-/blob/gimp-2-10/app/core/gimppalette-load.c#L39).

**Comment by ClarkThyLord** [comment]
You can now import files as VoxelSets like any other resource directly into Godot, now all that's left is adding the option to the VoxelSetEditor

**Comment by ClarkThyLord** [comment]
You can now import files into a VoxelSet with its editor overwriting or appending to it
