### ISSUE TITLE
Unable to load addon script from path

### ISSUE THREAD

**Issue by lo-vi** [ClarkThyLord/Voxel-Core#42]
Hello,

When I build godot with this module [https://github.com/Zylann/godot_voxel](url) I get the error,

`Unable to load addon script from path: 'res://addons/voxel-core/voxel-core.gd' There seems to be an error in the code, please check the syntax.`

With the output being:
` - res://addons/voxel-core/classes/voxel_set.gd:52 - Parse Error: Non-static function "set_name" can only be called from an instance.`
` - modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR`
` - res://addons/voxel-core/classes/voxel_object.gd:502 - Parse Error: The class "VoxelSet" couldn't be fully loaded (script error or cyclic dependency).`
` - modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR`
` -  res://addons/voxel-core/voxel-core.gd:17 - Parse Error: Couldn't fully preload the script, possible cyclic reference or compilation error. Use "load()" instead if a cyclic reference is intended.`
` - modules/gdscript/gdscript.cpp:583 - Method failed. Returning: ERR_PARSE_ERROR`
 
Is there any way I could fix this?

**Comment by lo-vi** [comment]
The `Voxel` and `VoxelTool` variables where being shadowed. I just changed them to get it working again.

**Comment by ClarkThyLord** [comment]
Good to know, hadn't tried building with Zylann's godot_voxel module before. I'm interested in seeing how well they play together.
