### ISSUE TITLE
Color picker, isn't working

### ISSUE THREAD

**Issue by FrostDragonEmpire** [ClarkThyLord/Voxel-Core#43]
<img width="278" alt="Screen Shot 2021-04-18 at 5 58 24 PM" src="https://user-images.githubusercontent.com/34220271/115168468-d9c03b00-a06f-11eb-832a-d12f8974646c.png">

When ever I click outside of that grey box, the window closes so I can't choose a color or add to voxel set.

I have a Mac so maybe the formatting is different.

**Comment by ClarkThyLord** [comment]
Interesting, I know that some users, including myself, have had some issues with UI and screen resolution when working with Godot on Mac. Let me see if I can replicate this on my Mac, if I can I'll try to correct it. But before that three quick questions, what version of Godot are you using? Are you using the the default Godot editor theme? And what's your screen resolution?

**Comment by FrostDragonEmpire** [comment]
Godot version 3.2.3; 2880 x 1800; I am using the default

I have a found a temporary work around, by messing with some settings on the color picker, I was able to get the gray box so that it is under the parts I need now.

**Comment by ClarkThyLord** [comment]
I've gone ahead and merged some patches for this, everything should look good now on Mac 👍

With that I'll close this issue for now, if there are any future UI issues go ahead and create a new issue, thanks.
