### ISSUE TITLE
Feature Request: Import multiple objects from complex MagicaVoxel File 

### ISSUE THREAD

**Issue by Nekolumbia** [ClarkThyLord/Voxel-Core#47]
Hello, in my current project I am using MagicaVoxel to build all my characters and equipment.
I make use of MagicaVoxels Object/Group Outliner to seperate my assets into multiple parts, which I can then animate in Godot (eg. arms, legs, body...).

Currently, I export every object from the outliner into a seperate vox file, then import them, and adjust their relative positions manually. This can be rather time intensive for larger assets.

A very helpfull feature would be an import option, that makes it possible to import a vox file into multiple meshes, without loosing this seperation, and the parts relative positions. Maybe into a scene, which maintains the structure of the vox file.

**Comment by ClarkThyLord** [comment]
Thanks to @ElectronicBlueberry this is now possible 🎉
