### ISSUE TITLE
VoxelWorldSize does not exist

### ISSUE THREAD

**Issue by twoco** [ClarkThyLord/Voxel-Core#50]
In your examples you refer to `Voxel.VoxelWorldSize`. But this does not exist. (Invalid get index.)

Adding this to **voxel.gd** fixes it. Should be maybe variable.

```py
const VoxelWorldSize = 0.5
```

Great project btw. 👍

**Comment by ClarkThyLord** [comment]
Good catch, one of the recent pull request refectored Voxel class reworking the way VoxelWorldSize is defined. I refectored the plugin code, but forgot to refactor the examples I'll take a look later, thanks 🙌

**Comment by ClarkThyLord** [comment]
Examples have been refactored, and are working again, thanks again!
