### ISSUE TITLE
voxel set: UI for picking colors and textures keeps expanding

### ISSUE THREAD

**Issue by betalars** [ClarkThyLord/Voxel-Core#65]
VoxelSet-Editor UI popups for selecting colors and textures seem to "grow" when being used for configuring larger voxel sets (i.e. after opening/closing these windows a few times, they are comically big)

Restarting Godot resets their size to normal. 
![image](https://user-images.githubusercontent.com/18014034/196053663-50310aaa-f899-4521-ba47-c5bea12cd480.png)

**Comment by ClarkThyLord** [comment]
Should be resolved with Voxel-Core 3.2.0
